[package]
name = "cpusbfl"
version = "0.1.0"
edition = "2024"
description = "Spectrum-Based Fault Localization for General-Purpose Hardware Designs Using Software Fuzzers"

[features]
default = ["std"]
std = []

[dependencies]
libafl = { version = "0.15.4", features = ["prelude"] }
libafl_bolts ={ version = "0.15.4" }
clap = { version = "4.5.20", features = ["derive"] }
libc = "0.2"
md5 = "0.7"
rand = "0.8.5"
serde = { version = "1.0.228", default-features = false }
serde_json = { version = "1.0.149", default-features = false }
dtw_rs = "0.10.0"
ndarray = "0.17.2"
tempfile = "3"
goblin = "0.10"
riscv-codec = "0.4.0"
sv-parser = "0.13.5"

[lib]
name = "cpusbfl"
crate-type = ["staticlib"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true
